2018-12-22 14:21:10,378 root - WARNING - This will get logged to a file
2018-12-22 14:21:10,379 root - ERROR - Bert raised an error
2018-12-22 14:21:10,379 root - ERROR - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Vrijstaat\Documents\GitHub\Vrijstaat\vrijstaat.py", line 44, in <module>
    c = a / b
NameError: name 'a' is not defined
